version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dungeon-master
      - SPRING_DATASOURCE_USERNAME=dmadmin
      - SPRING_DATASOURCE_PASSWORD=111111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: 'dmadmin'
      POSTGRES_PASSWORD: '111111'
      POSTGRES_DB: 'dungeon-master'
      