ALTER TABLE IF EXISTS dm_user_roles DROP CONSTRAINT IF EXISTS FK9jv29t3wke5nmrss2t1ekk2bl;
ALTER TABLE IF EXISTS dm_user_roles DROP CONSTRAINT IF EXISTS FKale7hnu5j7ws8mx23tst4ir7u;

DROP TABLE IF EXISTS dm_role cAScade;
DROP TABLE IF EXISTS dm_user cAScade;
DROP TABLE IF EXISTS dm_user_roles cAScade;
DROP TABLE IF EXISTS note cAScade;
DROP TABLE IF EXISTS TABLE_game cAScade;

CREATE TABLE dm_role 
(
	id INTEGER NOT NULL,
	name VARCHAR(255), 
		PRIMARY KEY (id)
);
CREATE TABLE dm_user 
(
	id INTEGER generated BY DEFAULT AS identity,
	email VARCHAR(255), 
	pASsword VARCHAR(255), 
	username VARCHAR(255), 
		PRIMARY KEY (id)
);
CREATE TABLE dm_user_roles 
(
	user_id INTEGER NOT NULL, 
	roles_id INTEGER NOT NULL, 
		PRIMARY KEY (user_id, roles_id)
);
CREATE TABLE note 
(
	id INTEGER generated BY DEFAULT AS identity,
	name VARCHAR(255),
	notes VARCHAR(255), 
		PRIMARY KEY (id)
);
CREATE TABLE TABLE_game 
(
	id INTEGER generated BY DEFAULT AS identity,
	complectation VARCHAR(255),
	created_BY_user boolean, 
	name VARCHAR(255), 
	players_amount VARCHAR(255), 
	rools VARCHAR(255), 
	short_discriprion VARCHAR(255), 
		PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS dm_user_roles 
	ADD CONSTRAINT user_role_role_fk 
		foreign key (roles_id) references dm_role
ALTER TABLE IF EXISTS dm_user_roles 
	ADD CONSTRAINT user_role_user_fk 
	foreign key (user_id) references dm_user
